DROP DATABASE IF EXISTS pet;
CREATE DATABASE pet;
USE pet;

CREATE TABLE owner (
    oId INT NOT NULL AUTO_INCREMENT,
    oName VARCHAR(36) NOT NULL,
    Number VARCHAR(20) UNIQUE NOT NULL,
    PRIMARY KEY (oId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE pet (
    pId INT NOT NULL AUTO_INCREMENT,
    oId INT NOT NULL,
    pName VARCHAR(36) NOT NULL,
    birth date NOT NULL,
    kind VARCHAR(36) NOT NULL,
    PRIMARY KEY (pId),
    FOREIGN KEY (oId) REFERENCES owner (oId) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;